# This workflow will trigger automated tests of the UI using the Cypress framework

name: Cypress CI

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm start & npm run server
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
      - run: cypress run